/-
Copyright (c) 2026 Yongxi Lin. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yongxi Lin
-/
module

public import NKBesicovitch.Grassmannian.NormalLift
public import NKBesicovitch.Grassmannian.Measure

/-!
# Flag integration in orthogonal frame coordinates

Choose a unit normal and an orthonormal transverse frame. Adjoin the
normal line to an independent lower-dimensional plane, then rotate the
entire configuration by a Haar-distributed orthogonal operator. The
resulting plane has the canonical Grassmannian probability law.

This gives the flag integration identity needed for induction without
requiring a measurable choice of transverse frames over the sphere.
The line direction is the rotated normal, whose Haar distribution is
identified with normalized surface measure in `Geometry/SphereMeasure`.
-/

@[expose] public section

open MeasureTheory Submodule
open scoped ENNReal

namespace NKBesicovitch.Grassmannian

variable {n m k : ℕ} {v : EuclideanSpace ℝ (Fin n)}

/-- The plane generated by a lower-dimensional plane and the normal line in a rotated frame. -/
noncomputable def flagDirection (hv : ‖v‖ = 1)
    (b : EuclideanSpace ℝ (Fin m) ≃ₗᵢ[ℝ] (ℝ ∙ v)ᗮ)
    (p : Rotations n × Grassmannian m k) : Grassmannian n (k + 1) :=
  rotate p.1 (normalLift hv b p.2)

theorem continuous_flagDirection (hv : ‖v‖ = 1)
    (b : EuclideanSpace ℝ (Fin m) ≃ₗᵢ[ℝ] (ℝ ∙ v)ᗮ) :
    Continuous (flagDirection hv b (k := k)) :=
  continuous_rotate.comp (continuous_fst.prodMk ((continuous_normalLift hv b).comp continuous_snd))

theorem normal_mem_normalLift (hv : ‖v‖ = 1)
    (b : EuclideanSpace ℝ (Fin m) ≃ₗᵢ[ℝ] (ℝ ∙ v)ᗮ) (V : Grassmannian m k) :
    v ∈ (normalLift hv b V).val := by
  apply (mem_normalLift_iff hv b V v).mpr
  refine ⟨0, V.val.zero_mem, 1, ?_⟩
  simp only [normalCoordinatesWithBasis_apply, map_zero, Submodule.coe_zero, one_smul, zero_add]

theorem rotated_normal_mem_flagDirection (hv : ‖v‖ = 1)
    (b : EuclideanSpace ℝ (Fin m) ≃ₗᵢ[ℝ] (ℝ ∙ v)ᗮ)
    (p : Rotations n × Grassmannian m k) :
    Unitary.linearIsometryEquiv p.1 v ∈ (flagDirection hv b p).val :=
  ⟨v, normal_mem_normalLift hv b p.2, rfl⟩

/-- Integration over planes equals integration over Haar frames and lower-dimensional planes. -/
theorem lintegral_probability_flag (hkn : k + 1 ≤ n) (hkm : k ≤ m) (hv : ‖v‖ = 1)
    (b : EuclideanSpace ℝ (Fin m) ≃ₗᵢ[ℝ] (ℝ ∙ v)ᗮ)
    {f : Grassmannian n (k + 1) → ℝ≥0∞} (hf : Measurable f) :
    (∫⁻ W, f W ∂probability hkn) =
      ∫⁻ u, ∫⁻ V, f (flagDirection hv b (u, V)) ∂probability hkm ∂Rotations.probability n := by
  symm
  calc
    _ = ∫⁻ V, ∫⁻ u, f (flagDirection hv b (u, V))
        ∂Rotations.probability n ∂probability hkm :=
      lintegral_lintegral_swap (hf.comp (continuous_flagDirection hv b).measurable).aemeasurable
    _ = _ := by
      simp only [flagDirection, ← lintegral_probability hkn _ hf,
        lintegral_const, measure_univ, mul_one]

/-- The flag construction pushes the product probability to the canonical plane probability. -/
theorem measurePreserving_flagDirection (hkn : k + 1 ≤ n) (hkm : k ≤ m) (hv : ‖v‖ = 1)
    (b : EuclideanSpace ℝ (Fin m) ≃ₗᵢ[ℝ] (ℝ ∙ v)ᗮ) :
    MeasurePreserving (flagDirection hv b)
      ((Rotations.probability n).prod (probability hkm)) (probability hkn) := by
  have hm := (continuous_flagDirection hv b (k := k)).measurable
  refine ⟨hm, Measure.ext_of_lintegral _ fun f hf ↦ ?_⟩
  rw [lintegral_map hf hm]
  exact (lintegral_prod (fun z ↦ f (flagDirection hv b z)) (hf.comp hm).aemeasurable).trans
    (lintegral_probability_flag hkn hkm hv b hf).symm

end NKBesicovitch.Grassmannian
